Title = "workbench"

Personal = true #设置为true则为个人版，设置为false则为协作版

[Mysql]
    # 个人版地址
    [Mysql.Personal]
    Host = "127.0.0.1"
    Username = "root"
    Password = "0325"
    Database = "workbench"
    Port = 3306

    #协同版地址
    [Mysql.Teamwork]
    Host = "127.0.0.1"
    Username = "root"
    Password = "0325"
    Database = "workbench"
    Port = 3306

[Redis]
Host = "127.0.0.1"
Auth = "hiRainn"


